name: Update Checker

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Get Commit Hash
      id: getHash
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH repo
        cd repo
        echo "commitHash=$(git rev-parse HEAD)" >> $GITHUB_ENV

    - name: Compare Commit Hash
      id: cacheHash
      uses: actions/cache@v4
      with:
        path: .commitHash
        key: HEAD-${{ env.commitHash }}

    - name: Save New Commit Hash
      if: steps.cacheHash.outputs.cache-hit != 'true'
      run: |
        echo ${{ env.commitHash }} | tee .commitHash

    - name: Trigger build
      if: steps.cacheHash.outputs.cache-hit != 'true'
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
        event-type: Source Code Update

    - name: Delete Old Workflows (Keep 10)
      run: |
        gh run list --limit 200 --json databaseId,createdAt \
        | jq -r 'sort_by(.createdAt) | reverse | .[10:] | .[].databaseId' \
        | xargs -r -n1 gh run delete
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
